name: CD
on: [push]
branches:[ master ]

workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -uses: action/checkout@v2
      
      -name: Run a one-line script
      run:  echo "Hello, world!"
  
  
